spring.application.name=flightbooking

spring.datasource.url=jdbc:mysql://localhost:3306/flightbooking_system
spring.datasource.username=root
spring.datasource.password=Robin7@mysql

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
logging.level.org.hibernate.orm.jdbc.bind=TRACE


jwt.secretKey=dklnaslkdasd4a5sd1as1d56s1ad5334534532948832asd45asd1adasdsadsaasd5484151
refreshTokenValidity=7
